-- ============================================================
-- Manufacturing Plant Monitor - Database Schema (PostgreSQL)
-- Database engine: PostgreSQL
-- Management tool: pgAdmin
-- ============================================================
-- Run this script inside pgAdmin's Query Tool, or via psql:
--   psql -U postgres -f database/schema.sql
-- ============================================================

-- Create database (run as superuser / postgres role)
-- In pgAdmin: right-click Databases → Create → Database → name it manufacturing_monitor
-- Or via psql:
CREATE DATABASE manufacturing_monitor;

-- Connect to the database before running the rest
\c manufacturing_monitor;

-- ============================================================
-- sensor_readings table
-- Stores all readings received from the Python gateway via MQTT.
-- ============================================================

CREATE TABLE IF NOT EXISTS sensor_readings (

    -- Primary key (PostgreSQL GENERATED ALWAYS AS IDENTITY - equivalent of AUTO_INCREMENT)
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Device identifier (e.g. "ManufacturingPlantMonitor")
    device           VARCHAR(100) NOT NULL,

    -- Plant name (e.g. "Manufacturing Plant")
    plant            VARCHAR(150) NOT NULL,

    -- Raw MQ-2 analog sensor value (0-1023)
    -- This is NOT in ppm. It is a raw ADC reading.
    gas_value        INTEGER,

    -- MQ-2 digital output status: 'ALERT' or 'NORMAL'
    -- ALERT = digital pin LOW (gas/smoke detected above threshold)
    gas_status       VARCHAR(30),

    -- DHT11 temperature in Celsius
    temperature_c    DOUBLE PRECISION,

    -- DHT11 relative humidity percentage
    humidity_percent DOUBLE PRECISION,

    -- HC-SR04 distance in centimeters
    distance_cm      DOUBLE PRECISION,

    -- Timestamp as reported by the Python gateway
    -- Format from gateway: "yyyy-MM-dd HH:mm:ss"
    reading_timestamp TIMESTAMP,

    -- When this row was inserted into the database
    created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

-- ============================================================
-- Indexes for fast queries
-- ============================================================

-- Index for device-based queries
CREATE INDEX IF NOT EXISTS idx_device
    ON sensor_readings (device);

-- Index for time-range and ordering queries
CREATE INDEX IF NOT EXISTS idx_reading_timestamp
    ON sensor_readings (reading_timestamp);

-- Composite index for alert queries
CREATE INDEX IF NOT EXISTS idx_gas_status_timestamp
    ON sensor_readings (gas_status, reading_timestamp DESC);

-- ============================================================
-- Verify
-- ============================================================
SELECT table_name FROM information_schema.tables
WHERE table_schema = 'public' AND table_name = 'sensor_readings';

\d sensor_readings
